#!/usr/bin/env bash

# Install nginx on web server; Nginx should be listening on port 80

# Update package index
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall for nginx
sudo ufw allow "Nginx HTTP"

# Set ownership for the nginx index file
sudo chown $USER:$USER /var/www/html/index.nginx-debian.html

# Write "Hello World!" to the nginx index file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart nginx service
sudo systemctl restart nginx
